package fr.quentin.farmersdelight.item;

import net.minecraft.component.type.FoodComponent;

public class ModFoodComponents {
    public static final FoodComponent CABBAGE = new FoodComponent.Builder().nutrition(2).saturationModifier(0.4F).build();
    public static final FoodComponent TOMATO = new FoodComponent.Builder().nutrition(1).saturationModifier(0.3F).build();
    public static final FoodComponent ONION = new FoodComponent.Builder().nutrition(2).saturationModifier(0.4F).build();
    public static final FoodComponent FRIED_EGG = new FoodComponent.Builder().nutrition(4).saturationModifier(0.4F).build();
    public static final FoodComponent MILK_BOTTLE = new FoodComponent.Builder().alwaysEdible().build();
    public static final FoodComponent HOT_COCOA = new FoodComponent.Builder().alwaysEdible().build();
    public static final FoodComponent APPLE_CIDER = new FoodComponent.Builder().alwaysEdible().build();
    public static final FoodComponent MELON_JUICE = new FoodComponent.Builder().alwaysEdible().build();
    public static final FoodComponent TOMATO_SAUCE = new FoodComponent.Builder().nutrition(4).saturationModifier(0.4F).build();
    public static final FoodComponent WHEAT_DOUGH = new FoodComponent.Builder().nutrition(2).saturationModifier(0.3F).build();
    public static final FoodComponent RAW_PASTA = new FoodComponent.Builder().nutrition(2).saturationModifier(0.3F).build();
    public static final FoodComponent PUMPKIN_SLICE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.3F).build();
    public static final FoodComponent CABBAGE_LEAF = new FoodComponent.Builder().nutrition(1).saturationModifier(0.4F).build();
    public static final FoodComponent MINCED_BEEF = new FoodComponent.Builder().nutrition(2).saturationModifier(0.3F).build();
    public static final FoodComponent BEEF_PATTY = new FoodComponent.Builder().nutrition(4).saturationModifier(0.8F).build();
    public static final FoodComponent CHICKEN_CUTS = new FoodComponent.Builder().nutrition(1).saturationModifier(0.3F).build();
    public static final FoodComponent COOKED_CHICKEN_CUTS = new FoodComponent.Builder().nutrition(3).saturationModifier(0.6F).build();
    public static final FoodComponent BACON = new FoodComponent.Builder().nutrition(2).saturationModifier(0.3F).build();
    public static final FoodComponent COOKED_BACON = new FoodComponent.Builder().nutrition(4).saturationModifier(0.8F).build();
    public static final FoodComponent COD_SLICE = new FoodComponent.Builder().nutrition(1).saturationModifier(0.1F).build();
    public static final FoodComponent COOKED_COD_SLICE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.5F).build();
    public static final FoodComponent SALMON_SLICE = new FoodComponent.Builder().nutrition(1).saturationModifier(0.1F).build();
    public static final FoodComponent COOKED_SALMON_SLICE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.8F).build();
    public static final FoodComponent MUTTON_CHOPS = new FoodComponent.Builder().nutrition(1).saturationModifier(0.3F).build();
    public static final FoodComponent COOKED_MUTTON_CHOPS = new FoodComponent.Builder().nutrition(3).saturationModifier(0.8F).build();
    public static final FoodComponent HAM = new FoodComponent.Builder().nutrition(5).saturationModifier(0.3F).build();
    public static final FoodComponent SMOKED_HAM = new FoodComponent.Builder().nutrition(10).saturationModifier(0.8F).build();
    public static final FoodComponent PIE_CRUST = new FoodComponent.Builder().nutrition(2).saturationModifier(0.2F).build();
    public static final FoodComponent CAKE_SLICE = new FoodComponent.Builder().nutrition(2).saturationModifier(0.1F).build();
    public static final FoodComponent APPLE_PIE_SLICE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.3F).build();
    public static final FoodComponent SWEET_BERRY_CHEESECAKE_SLICE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.3F).build();
    public static final FoodComponent CHOCOLATE_PIE_SLICE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.3F).build();
    public static final FoodComponent SWEET_BERRY_COOKIE = new FoodComponent.Builder().nutrition(2).saturationModifier(0.1F).build();
    public static final FoodComponent HONEY_COOKIE = new FoodComponent.Builder().nutrition(2).saturationModifier(0.1F).build();
    public static final FoodComponent MELON_POPSICLE = new FoodComponent.Builder().nutrition(3).saturationModifier(0.2F).alwaysEdible().build();
    public static final FoodComponent GLOW_BERRY_CUSTARD = new FoodComponent.Builder().nutrition(7).saturationModifier(0.6F).alwaysEdible().build();
    public static final FoodComponent FRUIT_SALAD = new FoodComponent.Builder().nutrition(6).saturationModifier(0.6F).build();
    public static final FoodComponent MIXED_SALAD = new FoodComponent.Builder().nutrition(6).saturationModifier(0.6F).build();
    public static final FoodComponent NETHER_SALAD = new FoodComponent.Builder().nutrition(5).saturationModifier(0.4F).build();
    public static final FoodComponent BARBECUE_STICK = new FoodComponent.Builder().nutrition(8).saturationModifier(0.9F).build();
    public static final FoodComponent EGG_SANDWICH = new FoodComponent.Builder().nutrition(8).saturationModifier(0.8F).build();
    public static final FoodComponent CHICKEN_SANDWICH = new FoodComponent.Builder().nutrition(10).saturationModifier(0.8F).build();
    public static final FoodComponent HAMBURGER = new FoodComponent.Builder().nutrition(11).saturationModifier(0.8F).build();
    public static final FoodComponent BACON_SANDWICH = new FoodComponent.Builder().nutrition(10).saturationModifier(0.8F).build();
    public static final FoodComponent MUTTON_WRAP = new FoodComponent.Builder().nutrition(10).saturationModifier(0.8F).build();
    public static final FoodComponent DUMPLINGS = new FoodComponent.Builder().nutrition(8).saturationModifier(0.8F).build();
    public static final FoodComponent STUFFED_POTATO = new FoodComponent.Builder().nutrition(10).saturationModifier(0.7F).build();
    public static final FoodComponent CABBAGE_ROLLS = new FoodComponent.Builder().nutrition(5).saturationModifier(0.5F).build();
    public static final FoodComponent SALMON_ROLL = new FoodComponent.Builder().nutrition(7).saturationModifier(0.6F).build();
    public static final FoodComponent COD_ROLL = new FoodComponent.Builder().nutrition(7).saturationModifier(0.6F).build();
    public static final FoodComponent KELP_ROLL = new FoodComponent.Builder().nutrition(12).saturationModifier(0.6F).build();
    public static final FoodComponent KELP_ROLL_SLICE = new FoodComponent.Builder().nutrition(6).saturationModifier(0.5F).build();
}
